Add cdn id to the output
ringods/terraform-website-s3-cloudfront-route53 pull request #12
Opened 2017-09-07 16:27 UTC by bhgames

2017-09-07 19:35 UTC, ringods requested changes
Hello @bhgames, if you can update the `README.md` and document the output, I will gladly merge your PR.

2017-09-07 20:59 UTC, bhgames commented
@ringods done

2017-09-08 06:42 UTC, MattiasGees approved these changes

2017-09-08 07:52 UTC, ringods approved these changes

2017-09-08 07:55 UTC, merged