[WIP] bucket_name: add new variable bucket_name
ringods/terraform-website-s3-cloudfront-route53 pull request #4
Opened 2017-01-13 14:16 UTC by gaelL

This variable is here to be able to force the bucket name.

Remove the default behavior who name as site.$domain

2017-01-19 19:32 UTC, ringods commented
Hello @gaelL,

Your contribution is much appreciated. However, to have the README.md in sync with the implementation, can you extend the docs (examples + variable description) to reflect your changes?

Tnx.

2017-01-30 10:16 UTC, gaelL commented
Sorry it was expected to be an internal PR. If you are interested by this change, I will update the readme as well. Thx

2017-01-30 10:18 UTC, ringods commented
@gaelL please do and I will integrate it in the repo here.

2017-01-30 10:40 UTC, gaelL commented
done. I also add more information in the commit message

2017-01-30 10:46 UTC, ringods requested changes

2017-01-30 10:46 UTC, ringods commented on site-main/variables.tf
> +variable bucket_name {}
Can you make the module backwards compatible by setting the default value of the bucket_name to the calculated value it was before?

` "site.${replace("${var.domain}",".","-")}"`

2017-01-30 10:53 UTC, gaelL commented on site-main/variables.tf
> +variable bucket_name {}
In fact no, I tried but terraform can't have interpolation in default variable 

https://github.com/hashicorp/terraform/issues/4084

2017-04-19 15:18 UTC, merged