✨ Add variable for minimum TLS version
ringods/terraform-website-s3-cloudfront-route53 pull request #40
Opened 2020-05-19 09:29 UTC by jerr0328

We wanted to be able to set a minimum protocol version so that the [SSL Tester](https://www.ssllabs.com/ssltest/) would give us an A (as well as fulfilling company compliance requirements), so the minimum protocol version is now a variable with the same default as before. Existing users shouldn't see a change, but running this in TF for us with a custom value does correctly replace the value in-place.

2020-05-25 12:39 UTC, duboisph approved these changes

2020-05-25 13:08 UTC, iuriaranda requested changes
@jerr0328 thanks for your contribution. Your changes look good overall, although I think that the variable name could lead to confusion. I suggest to change it to something like `minimum_client_tls_protocol_version`.

Two reasons mainly:
- there are two TLS protocol versions used in this module, one for the client to CloudFront communication, and another one for CloudFront to backend. The second one is set [here](https://github.com/skyscrapers/terraform-website-s3-cloudfront-route53/blob/8064ee50bf0f3c8ff0817c399d1150ad04744bed/site-main/main.tf#L96) and it's not yet configurable, but the variable name could lead to confusion if we ever make that configurable.
- The variable name `minimum_protocol_version` is not descriptive enough by itself (i.e. "protocol version of what?")

2020-06-02 13:42 UTC, iuriaranda approved these changes

2020-06-02 13:42 UTC, merged

2020-06-02 13:47 UTC, iuriaranda commented
@jerr0328 Thanks again for your contribution. Your changes are available in the new release [5.1.0](https://github.com/skyscrapers/terraform-website-s3-cloudfront-route53/releases/tag/5.1.0)